<S> = token (<brs> token)*
<token> = section / content
section = br? h ws? (brs content)*
h = stars ws headline
<headline> = keyed / unkeyed
<keyed> = keyword ws unkeyed
<unkeyed> = prioritized / title
<prioritized> = priority ws title
<title> = (#"."+ ws* tags) / #".+"
stars = #"\*+"
keyword = #"TODO|DONE"
priority = <"[#"> #"[a-zA-Z]" <"]">
tags = <":"> (tag <":">)+ ws?
<tag> = #"[a-zA-Z0-9_@]+"
<ws> = <#"[^\S\r\n]+">
<brs> = (br br br br+) / (br br br+) / (br br+) / br+
br = <#"\r?\n">
<content> = #"^([^*].*)?"
